language: node_js

install:
  - npm install

script:
  - npm start
  - npm start
  - npm start
  - npm start
  - npm start

jobs:
  include:
    - stage: test
      os: linux
      node_js: '12'
    - stage: test
      os: osx
      node_js: '12'
    - stage: test
      os: osx
      node_js: '10'
